name: Build README
on:
  push:
    branches:
    - master
    paths-ignore:
    - README.md
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Generate README
      run: bash .github/scripts/generate_readme.sh
    - name: Commit and push README
      run: |
        git config user.name "README-bot"
        git config user.email "readme-bot@example.com"
        git add README.md
        git diff --staged --quiet && echo "No changes to README.md" || \
          (git commit -m "Auto-update README.md" && git push)
